/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_j_HelloJNI */

#ifndef _Included_com_j_HelloJNI
#define _Included_com_j_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_j_HelloJNI
 * Method:    sayHello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_j_HelloJNI_sayHello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
